### ISSUE TITLE
Sorting doesn't work correctly

### ISSUE THREAD

**Issue by bryantlin** [briangann/grafana-datatable-panel#117] opened 2020-07-29 01:42 UTC
Hi, I understand #104 is closed but I find the issue below. 

Original sort order: 

Column
-------------
1
9
12
82
13

After sorting (i.e. clicking the header "Column"), the data looks like:

Column
-------------
1
12
13
82
9

Does anyone run into the same problem? Or, am I missing something? 

Thanks!

**Comment by ccnoecker** [comment] 2020-08-03 12:06
I am also having this issue with version 1.0.2 and Grafana 7, weirdly an old version (0.0.9) on another instance (Grafana 6) still works fine.

**Comment by briangann** [comment] 2020-08-07 04:52
strange regression, will take a look

**Comment by welyss** [comment] 2020-08-19 06:45
same problem,
and
I print the columnType with `console.log('wys:' + columnType + ',text:' + this.table.columns[i].text);` in file DatatableRenderer.ts:429
![image](https://user-images.githubusercontent.com/7651126/90600650-87e9bb80-e229-11ea-9e41-ab36709f9b8c.png)
**So I think the problem is why the columnType of the Number Column 'Value' is undefined, And if I set the Value's columnType to 'num', Then it works.**
hope helpful

**Comment by aerosadegh** [comment] 2020-08-28 14:34
I have same problem.

**Comment by peterschristoph** [comment] 2020-08-31 14:20
Same here, also the datatype does not matter.

- grafana @ 7.1.5
- briangann-datatable-panel @ 1.0.2


Problem:

- 9
- 5
- 3
- 2
- 2
- 2

Next page:
- 2
- 2
- 16
- 1

**Comment by ezerog** [comment] 2020-09-01 08:14
It looks like sorting as string. This should be fixed asap.

**Comment by anthraxn8b** [comment] 2020-09-24 15:30
Would be great to have this fixed soon... Your plugin is currently my only chance to get CSV in Excel dialect :-)

**Comment by hokiepokedad2** [comment] 2020-09-25 18:38
I too have this problem.

**Comment by briangann** [comment] 2020-10-15 06:20
in progress, need good sample data to work with to verify though :)

**Comment by anthraxn8b** [comment] 2020-10-16 12:04
@briangann, use sample data with numbers ;-)

**Comment by aerosadegh** [comment] 2020-10-17 19:40
> in progress, need good sample data to work with to verify though :)


id | num | Country
-- | -- | --
1 | 95 | Chile
2 | 883 | US
3 | 79 | Indonesia
4 | 754 | Brazil
5 | 75 | Romania
6 | 73 | Turkey
7 | 61 | South-Africa
8 | 56 | Iraq
9 | 55 | Italy
10 | 53 | Czechia

**Comment by ezerog** [comment] 2020-12-08 07:19
any plan to resolve?

**Comment by briangann** [comment] 2020-12-10 14:53
yes, will prioritize this one along with a couple others over the next few days, thanks!

**Comment by ezerog** [comment] 2021-01-21 10:21
When will this be resolved? 😭

**Closed** 2022-07-28 01:52 UTC
Labels: bug
