### ISSUE TITLE
"_n" treated as a literal string for the URL

### ISSUE THREAD

**Issue by jericvizmanos** [briangann/grafana-datatable-panel#87] opened 2020-04-17 00:00 UTC
**What happened**: 
"_n" from "$__cell_n" treated as a literal string for the URL

**What you expected to happen**:
$__cell_n variable should pull in the value of the nth cell on the current row.

**How to reproduce it (as minimally and precisely as possible)**:
1. Use the visualization Datatable panel
2. In the visualization tab, select "clickable link" and in the URL enter "$__cell_n"
3. Click on it / Hover over it

**Original Issue:**
<img width="871" alt="Screen Shot 2020-04-16 at 4 58 25 PM" src="https://user-images.githubusercontent.com/58444570/79517655-ac2b5680-8003-11ea-8109-8b53a655b68f.png">

**My Repro:**
<img width="1772" alt="Screen Shot 2020-04-16 at 4 22 26 PM" src="https://user-images.githubusercontent.com/58444570/79517444-0b3c9b80-8003-11ea-9fd2-6d5d2bd7821f.png">

**Comment by jacobwilsonnet** [comment] 2020-05-06 19:34
It doesn't appear that this was fixed in v1.0.0

**Comment by briangann** [comment] 2020-05-28 19:59
confirmed, not working as intended

**Comment by briangann** [comment] 2020-06-28 03:01
fixed in 1.0.2, can reference any column from the same row

**Closed by briangann** 2020-06-28 03:01 UTC
Labels: bug
